language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio update

script:
- platformio run

before_deploy:
- openssl aes-256-cbc -K $encrypted_3903ce2608a1_key -iv $encrypted_3903ce2608a1_iv
  -in ./deploy_key.enc -out /tmp/deploy_key -d
- chmod 400 /tmp/deploy_key

deploy:
- provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master